services:
  minio:
    command:
    - server
    - /data
    - --console-address
    - ':9090'
    container_name: minio_latest
    environment:
      '"MINIO_ROOT_USER': ROOTNAME"
      '"MINIO_ROOT_PASSWORD': CHANGEME123"
    image: quay.io/minio/minio
    ports:
    - 9000:9000
    - 9090:9090
    volumes:
    - ~/minio/data:/data
  easypanel:
    stdin_open: true
    tty: true
    volumes:
        - '/etc/easypanel:/etc/easypanel'
        - '/var/run/docker.sock:/var/run/docker.sock:ro'
    image: easypanel/easypanel
    command: setup
    ports:
    - 8888:3000
  pathology_image_server:
    tty: true
    stdin_open: true
    container_name: pathology_image_server
    depends_on:
      - "minio"
      - "easypanel"
    build:
      context: .
      dockerfile: Dockerfile
version: '3'
